version: "3.8"

services: 
  webserver:
    build: .
    ports: 
      - "8080:80"
    depends_on: 
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ci_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes: 
       - ci_postgresdata:/var/lib/postgresql/data

volumes:
  ci_postgresdata:
    name: ci_postgresdata